title: Display an image on your SenseHAT
hero_image: images/banner.png
description: Display an image on the LED matrix of your SenseHAT
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Display an image on your SenseHAT
